name: Valentine's Script

on:
  push:
    branches:
      - main  # Runs on push to the main branch
  pull_request:
    branches:
      - main  # Runs on pull request to main branch

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all commits are available

      - name: Debug - List all files
        run: ls -R  # Check if the valentines_script.py file exists

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --force-reinstall -r requirements.txt

      - name: Run the Valentine's Script
        run: python valentines_script.py  # Adjust path if needed
