name: Run Valentine's Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository to get your files
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Step 3: Install dependencies (e.g., Pillow for image generation)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow  # Install Pillow

    # Step 4: Debug: List files in the current directory
    - name: Debug: List files in the current directory
      run: |
        pwd  # Print working directory
        ls -l  # List files in the directory

    # Step 5: Run the script and check if everything is working
    - name: Run the script
      run: |
        # Debug: Ensure the image is being created
        python -c "
import os
from PIL import Image

# Path for the image
image_path = 'valentine_fireworks.png'

# Generate the image (you can replace this with your full script logic)
img = Image.new('RGB', (100, 100), color='red')
img.save(image_path)

# Check if the image file exists
if os.path.exists(image_path):
    print('Image was created successfully!')
else:
    print('Failed to create image.')
        "
        
    # Step 6: Add error handling to capture any issues in the script
    - name: Run the main Valentine's script with error handling
      run: |
        python -c "
try:
    # Replace this with your actual script logic
    from PIL import Image
    img = Image.new('RGB', (100, 100), color='red')
    img.save('valentine_fireworks.png')

    # Check if the image was created
    if not os.path.exists('valentine_fireworks.png'):
        raise Exception('Image not created.')

    print('Image created successfully!')

except Exception as e:
    print(f'Error occurred: {e}')
    exit(1)
        "
        
    # Step 7: If you need to upload artifacts (like the image), you can add this
    - name: Upload image as artifact (optional)
      uses: actions/upload-artifact@v3
      with:
        name: valentine-fireworks-image
        path: valentine_fireworks.png
