name: Run Valentine's Script

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:  # Allows you to trigger it manually from the Actions tab

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can choose another version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow  # Install Pillow for image generation

    - name: Run the Valentine's script
      run: |
        python scripts/valentines_script.py  # Run the script from the 'scripts' folder

    - name: Upload image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: valentine-fireworks-image
        path: valentines/valentine_fireworks.png  # Path to the generated image
