name: Run Valentine's Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository to get your files
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Step 3: Install dependencies (e.g., Pillow for image generation)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow  # Install Pillow

    # Step 4: Run the Valentine's script from the scripts folder
    - name: Run the Valentine's script
      run: |
        python scripts/valentines_script.py  # Updated to reflect the path

    # Step 5: Upload image as artifact using v4
    - name: Upload image as artifact
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: valentine-fireworks-image
        path: valentine_fireworks.png
